[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
merkle_distributor = "4nFsEC3VPbU13QpNCqbkQVbPm8HHZp1njqnL5YDruuAn"

[[test.genesis]]
address = "4DUapvWZDDCkfWJpdwvX2QjwAE9Yq4wU8792RMMv7Csg"
program = "./deps/zeta-staking/target/deploy/zeta_staking.so"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"

