anchor_version = "0.24.2"
solana_version = "1.9.0"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
merkle_distributor = "AKnD97G9JDc334HV3ZoQoj79ogJDVsjaAW5UGPHraSvZ"

[programs.devnet]
merkle_distributor = "51WuMUGPN9dR8Fu9jtn8ZZokfjq13uBYhRBRWn3sZyvR"

[programs.testnet]
merkle_distributor = "51WuMUGPN9dR8Fu9jtn8ZZokfjq13uBYhRBRWn3sZyvR"

[programs.localnet]
merkle_distributor = "51WuMUGPN9dR8Fu9jtn8ZZokfjq13uBYhRBRWn3sZyvR"

[scripts]
test = "yarn mocha"
